global:
  scrape_interval: 5s 
  evaluation_interval: 15s 
  

rule_files:
  - 'alerts_reactor.yml'

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'reactor-producer'
    static_configs:
      - targets: ['localhost:8000']